### ISSUE TITLE
Can't install app from Play Store

### ISSUE THREAD

**Issue by bielej** [sbs20/filenotes-android#2]
Play Store won't allow installing app on my OnePlus 3T.
I see a few solutions:
- Disable device restriction 
- Publish app on F-Droid
- Release a APK file

BTW: Great app! :+1:

**Comment by sbs20** [comment]
Hey! Thank you! And thanks for taking the time to get in touch. Sorry to hear you're having trouble installing.

I may well release the APK on here. What happens when you try and install? I've just checked and I haven't applied any device restrictions - and it *seems* as if the OnePlus 3T is supported (I use the OnePlus X).

HOWEVER - for some reason, I only made the app available in 5 countries - I have no idea what I was thinking. So I've just made it available to all countries / territories. Perhaps you could give it another go in about 12-24 hours to see if it works!

**Comment by bielej** [comment]
Yup, that was it.
I can install the app from Play Store.
